/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.text.Normalizer;
//import java.lang.Math;
import javax.swing.JFileChooser;
/**
 *
 * @author angeltucubal
 */

    
public class frm_JAVA extends javax.swing.JFrame implements ClipboardOwner {
    
    JFileChooser sele=new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    
    

    /**
     * Creates new form frm_JAVA
     */
    
    public static String texto;
    public frm_JAVA() {
        initComponents();
        this.setLocationRelativeTo(null);
        //operaciones op = new operaciones();
        //op.show();
    }
    public void setClipboard(String texto){
        StringSelection txt= new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
    }
    
    public void setClipboard2(String texto){
        StringSelection selection = new StringSelection(this.txt_entreda.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);  
        this.txt_entreda.setText("");
    }
    
    public void setClipboard3(String texto){
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    DataFlavor flavor = DataFlavor.stringFlavor;
    if (clipboard.isDataFlavorAvailable(flavor)) {
    try {
    String text = (String) clipboard.getData(flavor);
    this.txt_entreda.setText(text);
    } catch (UnsupportedFlavorException e) {
    System.out.println(e);
    } catch (IOException e) {
    System.out.println(e);
    }
    }   
    }
    
   
    
    
    //empieza
    public String AbrirArchivo(File archivo){
    String documento="";
    try{
        entrada =new FileInputStream(archivo);
        int ascci;
        while((ascci=entrada.read())!=-1){
            char caracter=(char)ascci;
            documento+=caracter;
        }
    } catch (Exception e){
    }
    return documento;
    }
    
    public String GuardarArchivo(File archivo,String documento){
    String mensaje=null;
    try{
    salida=new FileOutputStream(archivo);
    byte[] bytxt=documento.getBytes();
    salida.write(bytxt);
    mensaje="Archivo Guardado";
    } catch (Exception e){
    }
    return mensaje;
    }
    
    public String Guardar(File archivo,String documento){
    String mensaje=null;
    try{
    salida=new FileOutputStream(archivo);
    byte[] bytxt=documento.getBytes();
    salida.write(bytxt);
    mensaje="Archivo Guardado";
    } catch (Exception e){
    }
    return mensaje;
    }
    
    //termina

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_entreda = new javax.swing.JTextArea();
        btn_procesar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_salida = new javax.swing.JTextArea();
        lbl_rei = new javax.swing.JLabel();
        lbl_primera = new javax.swing.JLabel();
        txt_palabras = new javax.swing.JLabel();
        lbl_central = new javax.swing.JLabel();
        lbl_ul_pa = new javax.swing.JLabel();
        lbl_ultima = new javax.swing.JLabel();
        lbl_pri_pa = new javax.swing.JLabel();
        lbl_pa_cen = new javax.swing.JLabel();
        txt_longitud = new javax.swing.JLabel();
        lbl_reo = new javax.swing.JLabel();
        lbl_rea = new javax.swing.JLabel();
        lbl_reu = new javax.swing.JLabel();
        lbl_impar = new javax.swing.JLabel();
        lbl_ree = new javax.swing.JLabel();
        lbl_par = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_abrir = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btn_copiar = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANEJO DE CADENAS");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese un texto o abra un archivo");

        txt_entreda.setBackground(new java.awt.Color(87, 185, 189));
        txt_entreda.setColumns(20);
        txt_entreda.setLineWrap(true);
        txt_entreda.setRows(5);
        jScrollPane1.setViewportView(txt_entreda);

        btn_procesar.setBackground(new java.awt.Color(87, 185, 189));
        btn_procesar.setForeground(new java.awt.Color(87, 185, 189));
        btn_procesar.setText("Procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRADUCCIÓN A CLAVE MURCIELAGO");

        txt_salida.setBackground(new java.awt.Color(87, 185, 189));
        txt_salida.setColumns(20);
        txt_salida.setLineWrap(true);
        txt_salida.setRows(5);
        jScrollPane2.setViewportView(txt_salida);

        lbl_rei.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_rei.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones de \"I\",\"i\",\"o\",\"í\"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_primera.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_primera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primera letra del texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        txt_palabras.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_palabras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total de palabras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_central.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_central.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Letra central del texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_ul_pa.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_ul_pa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Última palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_ultima.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_ultima.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Última letra del texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_pri_pa.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_pri_pa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primera palabra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_pa_cen.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_pa_cen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Palabra central", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        txt_longitud.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txt_longitud.setText("            ");
        txt_longitud.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Longitud del texto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_reo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_reo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones de \"O\",\"o\",\"ó\",\"ó\"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_rea.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_rea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones de \"A\",\"a\",\"ó\",\"á\"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_reu.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_reu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones de \"Ú\",\"u\",\"ó\",\"ú\"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_impar.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_impar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caracte Impar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_ree.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_ree.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repeticiones de \"E\",\"e\",\"ó\",\"é\"", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        lbl_par.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lbl_par.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caracteristicas par:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_ul_pa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_reu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_pa_cen, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_reo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_pri_pa, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbl_rei, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_ultima, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_longitud, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_rea, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_ree, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lbl_primera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_procesar)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(114, 114, 114))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(466, Short.MAX_VALUE)
                    .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_procesar)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_longitud, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lbl_pri_pa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_rei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_reo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_reu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_pa_cen, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ul_pa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_rea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_primera, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ultima, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ree, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_central, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_impar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(430, Short.MAX_VALUE)
                    .addComponent(lbl_par, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(214, 214, 214)))
        );

        jMenu1.setText("Archivo");

        item_abrir.setText("Abrir                        Ctrl+A");
        item_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_abrirActionPerformed(evt);
            }
        });
        jMenu1.add(item_abrir);

        jMenuItem2.setText("Guardar                   Ctrl+G");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como        F12");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        btn_copiar.setText("Copiar                 Ctrl+C");
        btn_copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copiarActionPerformed(evt);
            }
        });
        jMenu2.add(btn_copiar);

        jMenuItem5.setText("Cortar                 Ctrl+X");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Pegar                  Ctrl+P");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Buscar                 Ctrl+B");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Reemplazar        Ctrl+R");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_abrirActionPerformed
        // TODO add your handling code here:
        if(sele.showDialog(null, "Abrir")==JFileChooser.APPROVE_OPTION){
        archivo=sele.getSelectedFile();
        if(archivo.canRead()){
        if(archivo.getName().endsWith("txt")){
            String documento=AbrirArchivo(archivo);
            txt_entreda.setText(documento);   
        }else{
            JOptionPane.showMessageDialog(null, "Archivo No Compatible");
        }
        }
        }
    }//GEN-LAST:event_item_abrirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
          if (sele.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
        archivo=sele.getSelectedFile();
        if(archivo.getName().endsWith("txt")){
            String Documento=txt_entreda.getText();
            Guardar(archivo, Documento);
            //if(mensaje!=null){
              //  JOptionPane.showMessageDialog(null, mensaje);
            //}//else{
            //JOptionPane.showMessageDialog(null, "Archivo No Compatible");
            //}
           }//else{
            //JOptionPane.showMessageDialog(null, "Guardar documento de Texto");
            //}
        }
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
          if (sele.showDialog(null, "Guardar")==JFileChooser.APPROVE_OPTION){
        archivo=sele.getSelectedFile();
        if(archivo.getName().endsWith("txt")){
            String Documento=txt_entreda.getText();
            String mensaje=GuardarArchivo(archivo, Documento);
            if(mensaje!=null){
                JOptionPane.showMessageDialog(null, mensaje);
            }else{
            JOptionPane.showMessageDialog(null, "Archivo No Compatible");
            }
           }else{
            JOptionPane.showMessageDialog(null, "Guardar documento de Texto");
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_copiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copiarActionPerformed
        // TODO add your handling code here:
        setClipboard(txt_entreda.getText());
    }//GEN-LAST:event_btn_copiarActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        /*StringSelection selection = new StringSelection(this.txt_entreda.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, selection);  
        this.txt_entreda.setText("");*/
        
        setClipboard2(txt_entreda.getText());
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        setClipboard3(txt_entreda.getText());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        frm_Buscar frm = new frm_Buscar();
        frm.setVisible(true);
        // frm_buscar1 frm = new frm_buscar1();
        //this.pd_escritorio.add(frm);
        //frm.show();
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
        // TODO add your handling code here:
        //this.lbl_par.setText("");
        
        this.lbl_par.setText("");
        this.lbl_impar.setText("");
        texto = txt_entreda.getText();
        String[] valor = txt_entreda.getText().split(" ");
        //this.lbl_pa_cen.setText("");
        //this.lbl_ul_pa.setText("");
        String[] chararray = texto.split("");
        //String texto1 = txt_entreda.getText().toUpperCase().trim();
        //String texto2 = txt_entreda.getText().toUpperCase().trim();
        //String texto3 = txt_entreda.getText().toUpperCase().trim();
        //String texto4 = txt_entreda.getText().toUpperCase().trim();
        //String texto5 = txt_entreda.getText().toUpperCase().trim();

        //int cont2=0;
        //cont2++;
        //int contador = 0,contador_a = 0,contador_e = 0,contador_i = 0,contador_o = 0,contador_u = 0;
           int contador=0;
           int cont1=0;
        //String resultado = "Texto:" + texto;
        //JOptionPane.showMessageDialog(null,resultado);
        //txt_salida.setText(texto);
        

        //PALABRAS
        StringTokenizer pa = new StringTokenizer(texto);
        txt_palabras.setText("" + pa.countTokens());

        //LONGITUD
        for(int l = 0; l < texto.length(); l++){
            contador++;
        }
        txt_longitud.setText(""+contador);

        //PRI_LETRA
        for (int i = 0; i < chararray.length; i++){
            lbl_primera.setText(chararray[0]);
            //  break;
        }
        //ULTIMA
        lbl_ultima.setText(chararray[contador-1]);

        //LET_CENTRAL
        
        int enmedio=contador/2;
        lbl_central.setText(chararray[enmedio]);

        //palabra central
        //int medio2 = contador2/2;
        //lbl_pa_cen.setText(textoarray[medio2]);

        //PRI_PALABRA
        for (int i = 0; i < valor.length; i++){
            lbl_pri_pa.setText(valor[0]);
            //break;
        }
        
        for (int i = 0; i < valor.length; i++){
            cont1 ++;
        }
        
        int p_mitad = cont1 / 2;
        this.lbl_pa_cen.setText(valor[p_mitad]);
        
        lbl_ul_pa.setText(valor[cont1-1]);
        
        new operaciones().Repa(texto,"a");
        
    //repeticiones en E
        new operaciones().Repe(texto,"e");
        //repeticiones en I
        new operaciones().Repi(texto,"i");
        //repeticiones en O
        new operaciones().Repo(texto,"o");
        //repeticiones en U
        new operaciones().Repu(texto,"u");
        //for (int i = 0; i < valor.length; i--){
            //  lbl_ul_pa.setText(valor[0]);
            // break;
            //}

        //int mitad2 = cont2/2;
        //lbl_pa_cen.setText(valor[mitad2]);

        //String[] texto = txt_entreda("[]+");

        //lbl_ul_pa.setText(valor[cont2 - 1]);

        // int mitad = dos / 2 ;
        //lbl_pa_cen.setText(textoa[ mitad ]);

        //lbl_ul_pa.setText(textoa[dos-1]);

        //palabra central
        //int enmedio1=contador1/2;
        //lbl_pa_cen.setText(textoarray[enmedio1]);
        //ULTIMA PALABRA
        //int tamano2 = 0;
        //lbl_ul_pa.setText(textoarray[contador2-1]);
        //for (int i = 0; i < textoarray.length; i--){
            //  lbl_ul_pa.setText(textoarray [i-1]);
            //return;
            //}

        /* for(int x = 0; x < texto1.length(); x++){
            //if(texto1.charAt(x) =='A' || texto1.charAt(x) =='a' /*||  texto.charAt(x) =='ó' || texto.charAt(x) =='á' ||*///){
              //  contador_a ++;
           // }

        //}
        //lbl_rea.setText(""+contador_a);
        //REPETI
        //for(int e = 0; e < texto2.length(); e++){
          //  if(texto2.charAt(e) =='E' || texto2.charAt(e) =='e' ||  texto2.charAt(e) =='é' /*|| texto.charAt(x) =='á' ||*/){
              //  contador_e++;
            //}
        /*}
        lbl_ree.setText(""+contador_e);
        for(int i = 0; i < texto3.length(); i++){
            //if(texto3.charAt(i) =='I' || texto3.charAt(i) =='i' ||  texto3.charAt(i) =='ó' /*|| texto.charAt(x) =='á' ||*///){
              //  contador_i++;
            //}
        //}
        /*lbl_rei.setText(""+contador_i);
        for(int o = 0; o < texto4.length(); o++){
          //  if(texto4.charAt(o) =='O' || texto4.charAt(o) =='o' ||  texto4.charAt(o) =='ó' /*|| texto.charAt(x) =='á' ||*///){
            //    contador_o++;
            //}
       // }
        //lbl_reo.setText(""+contador_o);
        //for(int u = 0; u < texto5.length(); u++){
          //  if(texto5.charAt(u) =='U' || texto5.charAt(u) =='u' ||  texto5.charAt(u) =='ó' /*|| texto.charAt(x) =='á' ||*/){
            //    contador_u++;
            //}
        //}
        //lbl_reu.setText(""+contador_u);*/

        //VALOR
        new operaciones().par_o_impar(texto);
        
        new Traductor().traductor(texto);
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        frm_Reemplazar frm = new frm_Reemplazar();
        frm.setVisible(true);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_JAVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_JAVA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_copiar;
    private javax.swing.JButton btn_procesar;
    public static javax.swing.JMenuItem item_abrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_central;
    public static javax.swing.JLabel lbl_impar;
    private javax.swing.JLabel lbl_pa_cen;
    public static javax.swing.JLabel lbl_par;
    private javax.swing.JLabel lbl_pri_pa;
    private javax.swing.JLabel lbl_primera;
    public static javax.swing.JLabel lbl_rea;
    public static javax.swing.JLabel lbl_ree;
    public static javax.swing.JLabel lbl_rei;
    public static javax.swing.JLabel lbl_reo;
    public static javax.swing.JLabel lbl_reu;
    private javax.swing.JLabel lbl_ul_pa;
    private javax.swing.JLabel lbl_ultima;
    public static javax.swing.JTextArea txt_entreda;
    private javax.swing.JLabel txt_longitud;
    private javax.swing.JLabel txt_palabras;
    public static javax.swing.JTextArea txt_salida;
    // End of variables declaration//GEN-END:variables

    private FileInputStream FileInputStream(File archivo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void lostOwnership(Clipboard clipboard, Transferable contents) {
    // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
